---
title: "Figure 3"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Figure 3}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval=FALSE}
library(CoreMicro)
library(patchwork)
library(ggplot2)
```


# Figure 2 (6-8-22)

```{r, eval=FALSE}
p3.1 <- arab_otu %>% CoreMicro::core_methods() %>% 
    core_venn(high= "#1B301E", low = "#E1E4E1") + 
  ggtitle(expression(paste("Shared Core Membership of ", italic("Arabidopsis")))) +
  theme(plot.title = element_text(size = 20, hjust = 0.5))  


ggsave("/Users/gordoncuster/Desktop/Quick_Sync/Manuscripts in progress/CoreCommunity/March22/figure2a.tiff", height = 8, width = 11)

p3.2 <- human_otu %>% core_methods() %>% 
 core_venn(low = "#EAE6f3", high = "#432976") +
  ggtitle("Shared Core Membership of HMBP") +
  theme(plot.title = element_text(size = 20, hjust = 0.5)) 


ggsave("/Users/gordoncuster/Desktop/Quick_Sync/Manuscripts in progress/CoreCommunity/March22/figure2b.tiff", height = 8, width = 11)

figure3 <- p3.2+ p3.1 + patchwork::plot_annotation(tag_levels = "A")#+ plot_layout(guides = "collect")

ggsave("/Users/gordoncuster/Desktop/Quick_Sync/Manuscripts in progress/CoreCommunity/March22/figure2.tiff", height = 9, width =22)
```
