---
title: "Figure 2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Figure 2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval=FALSE}
library(CoreMicro)
library(patchwork)
```

Create Human OTU and Arab OTU objects
```{r}
human<-readRDS(file = "../data/human_working_set.rda")

#extract dataframe and  prep dataframe for Core assignments
human_otu  <- data.frame(otu_table(human))
X <- rownames(human_otu)
human_otu<-cbind(X, human_otu)


#read in file
arabidopsis_m21_r<-readRDS(file = "../data/arabidopsis_m21_r.rda")

#extract dataframe and  prep dataframe for Core assignments
arab_otu  <- data.frame(otu_table(arabidopsis_m21_r))
X <- rownames(arab_otu)
arab_otu<-cbind(X, arab_otu)
```


# Figure 1 (6-8-22)

```{r, eval=FALSE}
p2.1 <- core_methods(human_otu) %>%
  core_plots(legend_title = "HMP Taxa Count") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

p2.2 <- core_methods(arab_otu) %>%
  core_plots(high= "#1B301E", 
             low = "#E1E4E1", 
             legend_title = "Arabidopsis Taxa Count")

figure2 <- p2.1 / p2.2 + patchwork::plot_annotation(tag_levels = "A")

ggsave("../FinalFigureOrder/Figures/Figure1.tiff", figure2, width = 14)
```


# Figure 3

```{r, eval=FALSE}
p3.1 <- arabidopsis %>% core_methods() %>% core_venn() + 
  ggtitle(expression(paste("Shared Core Membership of ", italic("Arabidopsis")))) +
  theme(plot.title = element_text(size = 20, hjust = 0.5)) +
  guides(fill = FALSE)

p3.2 <- human_stool %>% core_methods() %>% core_venn() + 
  ggtitle("Shared Core Membership of HMBP") +
  theme(plot.title = element_text(size = 20, hjust = 0.5))

figure3 <- p3.1 + p3.2

ggsave("inst/figures/figure3.tiff", figure3, height = 16, width = 23)
```

