---
title: "Figure 3"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Figure 3}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval=FALSE}
library(CoreMicro)
library(patchwork)
library(ggplot2)
```


Create Human OTU and Arab OTU objects
```{r}
human<-readRDS(file = "../../data/human_working_set.rda")

#extract dataframe and  prep dataframe for Core assignments
human_otu  <- data.frame(otu_table(human))
X <- rownames(human_otu)
human_otu<-cbind(X, human_otu)


#read in file
arabidopsis_m21_r<-readRDS(file = "../../data/arabidopsis_m21_r.rda")

#extract dataframe and  prep dataframe for Core assignments
arab_otu  <- data.frame(otu_table(arabidopsis_m21_r))
X <- rownames(arab_otu)
arab_otu<-cbind(X, arab_otu)
```




# Figure 2 (6-8-22)

```{r, eval=FALSE}
core_venn.core_methods <- function(combined_taxa_data,
                                   #doing this so I can remove the figures manually. 
                                     category_names = c("a",
                                                        "b",
                                                        "c",
                                                        "d"),
                                     low = "white",
                                     high = "#7E191B") {

    temp <-
      data.frame(combined_taxa_data) %>%
      dplyr::filter(.data$value == 1) %>%
      dplyr::select(.data$X, .data$name)

    temp <- lapply(split(temp, temp$name), `[[`, "X")

    suppressMessages(
      suppressWarnings(
        ggVennDiagram::ggVennDiagram(temp, category.names = category_names, set_size = 12, label_size = 10) +
          ggplot2::scale_fill_gradient(low=low,high = high) +
          scale_color_manual(values = rep("black", 4))
      )
    )

}
```


```{r}
arab_venn <- arab_otu %>% CoreMicro::core_methods() %>% 
    core_venn.core_methods(high= "#1B301E", low = "#E1E4E1") + 
  ggtitle(expression(paste("Shared Core Membership of ", italic("Arabidopsis")))) +
  theme(plot.title = element_text(size = 20, hjust = 0.5))  +
          scale_color_manual(values = rep("black", 4))  + guides(fill="none") + ggtitle("") + theme(plot.title = element_text(size = 30))
#ggsave("/Users/gordoncuster/Desktop/Quick_Sync/Manuscripts in progress/CoreCommunity/March22/figure2a.tiff", height = 8, width = 11)

#Add abundance information for core assignments, e.g., % core vs % non-core reads.
arab_otu$reads_per_taxa <- rowSums(arab_otu[,-1])
#assign membership to core
arab_assignments_SSR <- arab_otu %>% CoreMicro::core_methods() %>% as.data.frame() %>% dplyr::filter(name == "Summation of Sequence Reads") 
#join
arab_otu_joined_SSR <- full_join(arab_otu, arab_assignments_SSR) 

arab_assignments_HC <- arab_otu %>% CoreMicro::core_methods() %>% as.data.frame() %>% dplyr::filter(name == "Hard Cutoff") 
arab_otu_joined_HC <- full_join(arab_otu, arab_assignments_HC) 

arab_assignments_PRep <- arab_otu %>% CoreMicro::core_methods() %>% as.data.frame() %>% dplyr::filter(name == "Proportion of Sequence Replicates") 
arab_otu_joined_PRep <- full_join(arab_otu, arab_assignments_PRep) 

arab_assignments_PRR <- arab_otu %>% CoreMicro::core_methods() %>% as.data.frame() %>% dplyr::filter(name == "Proportion of Sequence Reads and Replicates") 
arab_otu_joined_PRR <- full_join(arab_otu, arab_assignments_PRR) 


stacked<-rbind(arab_otu_joined_SSR, arab_otu_joined_HC, arab_otu_joined_PRep, arab_otu_joined_PRR)

arab_abund_core_plot<-stacked %>% dplyr::select(reads_per_taxa, value, name) %>% ggplot( aes( fill=as.factor(value), y = reads_per_taxa, x = name)) +  geom_bar(position="fill", stat="identity") + ylab("Percent of total reads") + xlab("") +  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 22))  + scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 14)) + scale_fill_discrete(name ="Core \nmembership", labels=c('non-core', 'core'))  + theme_classic() + theme(axis.text.x=element_text(size=22))+ theme(axis.text.y=element_text(size=22)) + theme( axis.title.y = element_text(size = 30))  + theme(legend.text=element_text(size=22)) + theme(legend.title = element_text(size = 24))
#%>%
#%>%

```


```{r}

human_venn <- human_otu %>% core_methods() %>% 
 core_venn.core_methods(low = "#EAE6f3", high = "#432976") +
  ggtitle("") +
  theme(plot.title = element_text(size = 20, hjust = 0.5)) +
          scale_color_manual(values = rep("black", 4)) + guides(fill="none")  + theme(plot.title = element_text(size = 30)) 
          
          
#Add abundance information for core assignments, e.g., % core vs % non-core reads.
human_otu$reads_per_taxa <- rowSums(human_otu[,-1])
#assign membership to core
human_assignments_SSR <- human_otu %>% CoreMicro::core_methods() %>% as.data.frame() %>% dplyr::filter(name == "Summation of Sequence Reads") 
#join
human_otu_joined_SSR <- full_join(human_otu, human_assignments_SSR) 

human_assignments_HC <- human_otu %>% CoreMicro::core_methods() %>% as.data.frame() %>% dplyr::filter(name == "Hard Cutoff") 
human_otu_joined_HC <- full_join(human_otu, human_assignments_HC) 

human_assignments_PRep <- human_otu %>% CoreMicro::core_methods() %>% as.data.frame() %>% dplyr::filter(name == "Proportion of Sequence Replicates") 
human_otu_joined_PRep <- full_join(human_otu, human_assignments_PRep) 

human_assignments_PRR <- human_otu %>% CoreMicro::core_methods() %>% as.data.frame() %>% dplyr::filter(name == "Proportion of Sequence Reads and Replicates") 
human_otu_joined_PRR <- full_join(human_otu, human_assignments_PRR) 


stacked<-rbind(human_otu_joined_SSR, human_otu_joined_HC, human_otu_joined_PRep, human_otu_joined_PRR)

human_abund_core_plot<-stacked %>% dplyr::select(reads_per_taxa, value, name) %>% ggplot( aes( fill=as.factor(value), y = reads_per_taxa, x = name)) +  geom_bar(position="fill", stat="identity") + ylab("Percent of total reads") + xlab("") +  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 22))  + scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 14)) + scale_fill_discrete(name ="Core \nmembership", labels=c('non-core', 'core'))  + theme_classic() + theme(axis.text.x=element_text(size=22))+ theme(axis.text.y=element_text(size=22)) + theme( axis.title.y = element_text(size = 30))  + theme(legend.text=element_text(size=22)) + theme(legend.title = element_text(size = 24))
#%>%
```


```{r}

#ggsave("/Users/gordoncuster/Desktop/Quick_Sync/Manuscripts in progress/CoreCommunity/March22/figure2b.tiff", height = 8, width = 11)

figure2 <- human_venn + arab_venn #+ patchwork::plot_annotation(tag_levels = "A")#+ plot_layout(guides = "collect")
ggsave("../FinalFigureOrder/Figures/Figure2a.tiff", height = 9, width =22)
figure2a <- human_abund_core_plot + arab_abund_core_plot + plot_layout(guides = "collect")
ggsave("../FinalFigureOrder/Figures/Figure2b.tiff", height = 9, width =22)



```
